### ISSUE TITLE
How do you combine 2 or more elements of state?

### ISSUE THREAD

**Issue by larten** [OlegSheliakin/state-binder#1]
So first of all, thank you for this great stuff!
It's much pretty, than the previous solution what I used for it.

On the screen sometimes there are parts, which depend on more data, but I also use these data alone on different parts.
I guess it will be cool if I could bind 2 or more part of state to avoid unnecessary redundant data it the viewstate.

I will try to extend the library with this on this week, if I will have time, but I appreciate every ideas :)

**Comment by OlegSheliakin** [comment]
@larten 
You can combine properties if the same type: For example, you have a state:
``` kotlin
data class MyState(
   val flagFirst: Boolean,
   val flagSecond: Boolean
) : State
```

In your Activity/Fragment:

```kotlin

stateBinder.apply {
   bind({ it.firstFlag && it.secondFlag }) { flag ->
    //do your stuff 
   }
}
```

**Comment by larten** [comment]
Great, but these are mostly different

**Comment by OlegSheliakin** [comment]
It is even possible to combine different types of properties. 

Your state is:
``` kotlin
data class MyState(
   val flagFirst: Boolean,
   val text: String
) : State
```

You need to combine `firstFlag` and `text`, and react only when any of them changes or both.

``` kotlin
stateBinder.apply {
   bind({ Pair(it.flagFirst, it.text) }) { pair->
    //here comes Pair<Boolean, String>
   }
}
```

**Comment by larten** [comment]
Oh what easy :)
Thank you very much!
